### ISSUE TITLE
This plugin is stuck when checking for updates

### ISSUE THREAD

**Issue by KirroNeko** [JoelGodOfwar/ShulkerRespawner#1]
Hello author, I am from China. For some reason, my network connection will be stuck when your server checks for updates, and your plugin does not support turning off automatic check for updates, which will cause my server to freeze for a long time. Please add this feature. Also, your Chinese translation is wrong. Your Chinese configuration is Pinyin instead of Chinese characters. Chinese characters should be like this'你好世界'. I will be happy to help you if needed.
 I am sorry for my junk english.

**Comment by JoelGodOfwar** [comment]
Which versions of the plugin are you using? I did the Chinese translations using google, and at the time was not using UTF-8 so could not use the Chinese characters, this has changed, and if you have a proper translation I would love to change the plugin's Chinese translation.

**Comment by KirroNeko** [comment]
I am using version 1.13. The link below is my translation. Also, please update the option to turn off automatically check for updates.
https://pastebin.com/MNDLTDtw

**Comment by JoelGodOfwar** [comment]
Download version 1.13_1.0.3, which has the ability to turn auto_update_check to false.
I messed up on the first 2 versions and didn't have the plugin actually check the config for the value of auto_update_check, but it is fixed in the new version. I will release the new Chinese translations with the next version, after you answer this question.
wouldn't 临时切换调试值。be better than 临时打开Debug(调试)模式.?

**Comment by KirroNeko** [comment]
'临时切换调试值' will translate debugging into a value meaning.But I also need to correct my mistake, this should be translated into ‘临时切换Debug(调试)模式.’.

**Comment by KirroNeko** [comment]
New problem, version 1.0.3 is a configuration file. But I put auto_update_check: false. Still stuck, here is my error log.
https://pastebin.com/zXJHSjdw

**Comment by JoelGodOfwar** [comment]
Found what was causing your error, try this fixed version. https://github.com/JoelGodOfwar/ShulkerRespawner/raw/master/versioncheck/1.13/ShulkerRespawner-1.13_1.0.3.jar
