### ISSUE TITLE
Spaming shulker spawn message.

### ISSUE THREAD

**Issue by iusearch** [JoelGodOfwar/ShulkerRespawner#2]
For now, the shulker spawning message is not switched by debug. This cause tons of messages in server log. Hope to add an option to disable that.

**Comment by JoelGodOfwar** [comment]
I will be working on an update that includes this soon. I need to update the auto update check to be less laggy already, and will include this feature also.

**Comment by JoelGodOfwar** [comment]
issue resolved in 1.13_1.0.4
